FROM ubuntu:18.04
MAINTAINER ankur

RUN apt-get update && apt-get -y --force-yes install vim wget git unzip sudo software-properties-common python-minimal python-pip python3-dev supervisor
RUN apt-get install -y libboost-python-dev unixodbc-dev

ADD . /opt/
ADD infra_files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN pip install -r /opt/requirements/dev.txt

EXPOSE 5000
WORKDIR /opt
CMD ["/usr/bin/supervisord"]
